### ISSUE TITLE
Handle competitors stalling the clock

### ISSUE THREAD

**Issue by WillB97** [sourcebots/competition-simulator#11]
Since the simulator itself will be run in an mostly unattended fashion we need a method to detect and handle a competitors code stalling the clock. This happens when a robot's code enters a loop where no `robot.sleep()` call occurs and the exit condintion requires a sensor input to change.

On detecting that the clock has stalled it would be useful to be able to give the competitors the animation up until that point and a clear error message that simulator time was unable to advance.

**Comment by RealOrangeOne** [comment]
This is something we should solve in future for all modes, but for this case we can get away with just handling it in the UI, which is implemented in https://github.com/RealOrangeOne/simulator-runner/commit/1b80dd5de321990507fce5377c24295aa2b6e438
