### ISSUE TITLE
Select sensors present on each robot

### ISSUE THREAD

**Issue by WillB97** [sourcebots/competition-simulator#3]
We need to decide what sensors each robot has in order to sense: the tokens, the environment and other robots. Currently the tokens will have radio beacons to allow them to be detected.

Sensors provided previously include:
- Radio
- Compass
- Ultrasound
- Bump sensors
- Vision

See the [Webots API reference](https://cyberbotics.com/doc/reference/nodes-and-api-functions) for the sensors available in the simulator.

**Comment by WillB97** [comment]
Forklift:
- Compass
- Radio
- Ultrasound
  - 1 Front
  - 1 each side
  - 1 at the front of each arm
  - 1 rear
  - 1 facing through grabber
- touch sensor on rear
- encoders on wheels
- position sensor on grabber

**Comment by WillB97** [comment]
My feeling for the crane is:
- Radio
- encoders on all 3 axis
- touch sensor on grabber

We could also add a radio link for the crane and forklift to send information between them.

**Comment by sedders123** [comment]
We agree that Radio, encoders and a touch sensor are probably all we need.
