### ISSUE TITLE
Create tokens

### ISSUE THREAD

**Issue by WillB97** [sourcebots/competition-simulator#7]
These will likely be cube or cuboid shape with someway the identify which team they belong to.
Additional tweaking will also be needed to the mass and physics damping to reduce the issues with tokens being ejected.
To allow the tokens to be picked up by the crane, [connectors](https://cyberbotics.com/doc/reference/connector) need to be added to all the faces.

**Comment by WillB97** [comment]
There are some complications with this as Emitter nodes need to be within a robot and I can't get separate solids within a robot to be independent. So it looks like we will need an individual controller for each token which is likely to be a significant performance hit.

**Comment by WillB97** [comment]
Having thought about it there are three options we can pursue here:
1. Find a way to have solids under the same Robot node move independently
2. Make each token a separate robot and controller which just transmits a fixed message
3. have only the emitters under the token controller and use supervisor functions to keep them at the center of the tokens.

**Comment by sedders123** [comment]
>Find a way to have solids under the same Robot node move independently

Could we ask about this on the Webots Discord?

**Comment by WillB97** [comment]
I've asked in the Discord and option 1 is very awkward, you might be able to do it by having a linear actuator for each axis connecting each token to the root.
